# Generated by Django 6.0.1 on 2026-02-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_pulished',
            new_name='is_published',
        ),
    ]
